services:
  - type: web
    name: mallick-enterprise
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ADMIN_SECRET
        value: officekart@123
